import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Footer } from "@/layout/footer";
import { Header } from "@/layout/header";

export const metadata: Metadata = {
  title: "DevMint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
